controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: velocity_controllers/JointGroupVelocityController

gripper_controller:
  ros__parameters:
    joints:
      - gripper_vertical_joint
      - gripper_finger_left_joint
      - gripper_finger_right_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity